name: CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build-windows:
    name: Build (Windows)
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >
            git
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-cmake
            zip
            unzip
            make

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake .. -DWIN32=1 -DMSYS=1 -DMINGW=1 -G"MSYS Makefiles"

      - name: Build
        run: |
          cd build
          cmake --build .

      - name: Package
        run: |
          zip -r build.zip build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: build.zip

  build-linux:
    name: Build (Linux)
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            zip \
            build-essential

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          cmake --build .

      - name: Package
        run: |
          zip -r build.zip build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: build.zip

  build-macos-arm:
    name: Build (macOS ARM)
    runs-on: macos-26

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          cmake --build .

      - name: Package
        run: |
          zip -r build.zip build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm
          path: build.zip

  build-macos-intel:
    name: Build (macOS Intel)
    runs-on: macos-15-intel

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          cmake --build .

      - name: Package
        run: |
          zip -r build.zip build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-intel
          path: build.zip
